# Don't change the line below!
#! oxygen_storefront_id: 1000009650

name: Storefront 1000009650
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build and Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@vdo-not-use-unstable
        env:
          UNSAFE_OXYGEN_DEPLOYMENT_URL: https://bundle-size.tunnel.up.dev
        with:
          oxygen_deployment_token: eyJhY2Nlc3NfdG9rZW4iOiJhdGtuX2ZjYWFhOWNiYjg3ZDNmOTE4Mjk3NWE5MDNlY2E0NzFhMmUxMGU0MmFkYjE1MDNkN2M4YjU4ODk1NGZiZDg1OWYiLCJleHBpcmVzX2F0IjoiMjAyNC0xMi0xM1QwMzoxNDoyMy42MTVaIiwiY2xpZW50IjoiZ2lkOi8vb3h5Z2VuLWh1Yi9DbGllbnQvMSIsImFsbG93ZWRfcmVzb3VyY2UiOiJnaWQ6Ly9veHlnZW4taHViL0FwcC8xIiwibmFtZXNwYWNlX2lkIjoiZ2lkOi8vb3h5Z2VuLWh1Yi9OYW1lc3BhY2UvMSIsIm5hbWVzcGFjZSI6IjEiLCJhcHBfaWQiOiJnaWQ6Ly9veHlnZW4taHViL0FwcC8xIn0=
          build_command: "npm run build"
          oxygen_deployment_verification: false

      # Create GitHub Deployment
      - name: Create GitHub Deployment
        uses: shopify/github-deployment-action@v1
        if: always()
        with:
          token: ${{ github.token }}
          environment: 'preview'
          preview_url: ${{ steps.deploy.outputs.url }}
          description: ${{ github.event.head_commit.message }}
